name: Build and deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: BingyanStudio/actions/.github/workflows/build-and-push-image.yaml@main
    with:
      name: bingyan-badge
      tag: ${{ github.sha }}

  deploy:
    needs: build
    uses: BingyanStudio/actions/.github/workflows/update-deployment.yaml@main
    with:
      name: bingyan-badge
      namespace: bingyan-badge
      tag: ${{ github.sha }}
      filename: bingyan-badge.yaml
